"""Step 2 smoke test: schema + repository round-trip and idempotency.

Runs against the live biorag database and cleans up after itself:

    docker compose exec airflow-worker python /opt/biorag/tests/test_pipeline_db.py

Proves the properties the whole pipeline depends on - re-ingesting a paper is a
no-op, a new arXiv version re-opens it, and chunks never double-insert.
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone

from biorag_pipeline import db, repository as repo
from biorag_pipeline.repository import ChunkRecord, PaperRecord, RunCounters

TEST_ID = "0000.99999"          # never a real arXiv id
TEST_RUN = "smoke_test_run"

passed = 0


def check(label: str, condition: bool) -> None:
    global passed
    if condition:
        passed += 1
        print(f"  PASS  {label}")
    else:
        print(f"  FAIL  {label}")
        raise AssertionError(label)


def make_paper(version: int = 1) -> PaperRecord:
    return PaperRecord(
        arxiv_id=TEST_ID,
        version=version,
        title=f"Synthetic Paper v{version}",
        abstract="An abstract used only by the smoke test.",
        authors=["Ada Lovelace", "Alan Turing"],
        categories=["q-bio.QM", "cs.LG"],
        primary_category="q-bio.QM",
        published_at=datetime(2026, 9, 1, tzinfo=timezone.utc),
        pdf_url=f"https://arxiv.org/pdf/{TEST_ID}v{version}",
    )


def make_chunks(n: int) -> list[ChunkRecord]:
    return [
        ChunkRecord(
            chunk_id=f"smoke{i:07d}",
            ordinal=i,
            text=f"Chunk number {i} of the synthetic paper.",
            section="Methods" if i % 2 else "Results",
            char_start=i * 500,
            char_end=(i + 1) * 500,
            n_tokens=7,
        )
        for i in range(n)
    ]


def cleanup(conn) -> None:
    with conn.cursor() as cur:
        cur.execute("DELETE FROM ingest_errors WHERE run_id = %s", (TEST_RUN,))
        cur.execute("DELETE FROM ingest_runs   WHERE run_id = %s", (TEST_RUN,))
        cur.execute("DELETE FROM papers        WHERE arxiv_id = %s", (TEST_ID,))


def main() -> int:
    with db.connect() as conn:
        cleanup(conn)   # leftovers from a previous failed run

        print("\n-- papers: upsert semantics --")
        check("new paper inserts",
              repo.upsert_paper(conn, make_paper(1), TEST_RUN) == "inserted")
        check("same version is a no-op",
              repo.upsert_paper(conn, make_paper(1), TEST_RUN) == "unchanged")
        check("newer version updates",
              repo.upsert_paper(conn, make_paper(2), TEST_RUN) == "updated")
        check("older version is ignored",
              repo.upsert_paper(conn, make_paper(1), TEST_RUN) == "unchanged")

        row = repo.get_paper(conn, TEST_ID)
        check("version advanced to 2", row["version"] == 2)
        check("doc_id generated by the database",
              row["doc_id"] == f"arxiv_{TEST_ID}")
        check("update reset status to discovered",
              row["status"] == "discovered")
        check("array columns round-trip",
              row["authors"] == ["Ada Lovelace", "Alan Turing"])

        print("\n-- papers: lifecycle --")
        repo.mark_paper(conn, TEST_ID, "fetched", raw_path="/opt/biorag/var/raw/x.pdf")
        check("status advanced",
              repo.get_paper(conn, TEST_ID)["status"] == "fetched")
        check("papers_by_status finds it",
              any(p["arxiv_id"] == TEST_ID
                  for p in repo.papers_by_status(conn, "fetched")))

        print("\n-- papers: content hash --")
        check("unknown hash counts as changed",
              repo.content_changed(conn, TEST_ID, "hash_a") is True)
        repo.mark_paper(conn, TEST_ID, "parsed", content_hash="hash_a")
        check("same hash is unchanged",
              repo.content_changed(conn, TEST_ID, "hash_a") is False)
        check("different hash is changed",
              repo.content_changed(conn, TEST_ID, "hash_b") is True)
        check("raw_path survived the second mark_paper",
              repo.get_paper(conn, TEST_ID)["raw_path"] is not None)

        print("\n-- chunks: replace is idempotent --")
        check("first write returns 3",
              repo.replace_chunks(conn, TEST_ID, make_chunks(3)) == 3)
        check("n_chunks denormalised",
              repo.get_paper(conn, TEST_ID)["n_chunks"] == 3)
        repo.replace_chunks(conn, TEST_ID, make_chunks(3))
        check("re-write leaves 3 rows, not 6",
              len(repo.pending_chunks(conn)) == 3)
        check("shrinking to 2 drops the third",
              repo.replace_chunks(conn, TEST_ID, make_chunks(2)) == 2)
        check("pending reflects the shrink",
              len(repo.pending_chunks(conn)) == 2)

        print("\n-- chunks: embedding queue --")
        pending = repo.pending_chunks(conn)
        check("join exposes doc_title", pending[0]["doc_title"].startswith("Synthetic"))
        check("join exposes doc_id", pending[0]["doc_id"] == f"arxiv_{TEST_ID}")
        check("marking one embedded returns 1",
              repo.mark_chunks_embedded(conn, [pending[0]["chunk_id"]]) == 1)
        check("queue shrinks to 1", len(repo.pending_chunks(conn)) == 1)
        check("empty list is safe", repo.mark_chunks_embedded(conn, []) == 0)

        print("\n-- runs and errors --")
        now = datetime.now(timezone.utc)
        repo.start_run(conn, TEST_RUN, "arxiv_ingest_daily", now,
                       categories=["q-bio.QM"])
        repo.start_run(conn, TEST_RUN, "arxiv_ingest_daily", now)  # re-run is safe
        repo.record_error(conn, TEST_RUN, "parse",
                          "pdf has no extractable text", TEST_ID)
        repo.finish_run(conn, TEST_RUN, "success",
                        RunCounters(n_discovered=1, n_indexed=1,
                                    n_chunks=2, n_failed=1))
        with conn.cursor() as cur:
            cur.execute("SELECT status, n_chunks FROM ingest_runs WHERE run_id=%s",
                        (TEST_RUN,))
            check("run closed with counters", cur.fetchone() == ("success", 2))
            cur.execute("SELECT count(*) FROM ingest_errors WHERE run_id=%s",
                        (TEST_RUN,))
            check("error recorded", cur.fetchone()[0] == 1)

        print("\n-- constraints --")
        stats = repo.corpus_stats(conn)
        check("corpus_stats returns all keys",
              set(stats) == {"papers", "papers_indexed", "papers_failed",
                             "chunks", "chunks_embedded", "chunks_pending"})

        with conn.cursor() as cur:
            cur.execute("DELETE FROM papers WHERE arxiv_id = %s", (TEST_ID,))
            cur.execute("SELECT count(*) FROM chunks WHERE arxiv_id = %s", (TEST_ID,))
            check("deleting a paper cascades to its chunks", cur.fetchone()[0] == 0)

        cleanup(conn)

    print(f"\n{passed} checks passed\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
